kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nginx-ingress-ota-claim
  namespace: ingress-nginx
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: nfs-client-provisioner
