kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: device-manage-api
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-client-provisioner
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: device-manage-api
  labels:
   app: device-manage-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: device-manage-api
  template: 
    metadata:
      labels:
        app: device-manage-api
    spec:
      #restartPolicy: Always
      containers:
      - name: device-manage-api
        image: device-manage-api:latest
        imagePullPolicy: IfNotPresent
#        resources:
#          limits:
#            memory: "1024Mi"
        ports:
        - containerPort: 8080
        env:
        - name : DB_NAME 
          value : devicedb
        - name : DB_PASSWORD 
          value : 1qaz2wsx
        - name : DB_POOL_SIZE
          value : "5"
        - name : DB_PORT
          value : "5432"
        - name : DB_SERVER
          value : 192.168.12.216
        - name : DB_USERNAME
          value : postgres
        - name : LOGGING_PATH
          value : /var/log/device-manager
        - name : SESSION_TOKEN_TTL
          value : "1800"
        - name : MEMCACHED_CACHE_SERVER
          value : memcache:11211
        - name : OTA_USR_TOKEN_API
          value : http://user-manage-api:8080/user-service-api
        - name : CACHE_LOG_LEVEL
          value : DEBUG
        - name : HTTP_REQ_LOG_LEVEL
          value : DEBUG
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 90 
          periodSeconds: 90
          timeoutSeconds: 90
        volumeMounts:
            - name: device-manager-log
              mountPath: "/var/log/device-manager" 
      volumes:
        - name: device-manager-log
          persistentVolumeClaim:
            claimName: device-manage-api
---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: device-manage-api
  name: device-manage-api
  #annotations:
  # traefik.ingress.kubernetes.io/load-balancer-method: drr
  # traefik.ingress.kubernetes.io/affinity: "true"
spec:
  #type: NodePort
  ports:
  - protocol: TCP 
    port: 8080
    targetPort: 8080
    #nodePort: 30002
  selector:
    app: device-manage-api
